# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoIi7KERqPxy8A4QKSGdHsI_jJKsg5Ja
"""

import pandas as pd
import joblib

model = joblib.load("/content/lightgbm_model.pkl")

def predict_condition(numeric_data):
    features = ["age", "glucose", "cholesterol", "blood_pressure", "bmi"]
    X = pd.DataFrame([[numeric_data[f] for f in features]], columns=features)
    prediction = model.predict(X)[0]
    return "Abnormal" if prediction == 1 else "Normal"